//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=appidentity.c6qpaqe4bu02.us-west-2.rds.amazonaws.com,1433;Initial Cat" +
            "alog=DoddleNow;Persist Security Info=True;User ID=DoddleNow;Password=gz983~1!I0x" +
            "X2%")]
        public string DoddleNowConnectionString {
            get {
                return ((string)(this["DoddleNowConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=appidentity.c6qpaqe4bu02.us-west-2.rds.amazonaws.com,1433;Initial Cat" +
            "alog=DoddleNow;Integrated Security=False;User ID=DoddleNow;Password=gz983~1!I0xX" +
            "2%;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False")]
        public string DoddleNowConnectionString1 {
            get {
                return ((string)(this["DoddleNowConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=appidentity.c6qpaqe4bu02.us-west-2.rds.amazonaws.com,1433;Initial Cat" +
            "alog=DoddleNow;Integrated Security=False;User ID=DoddleApplication;Password=[$C7" +
            "N!6jK;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False")]
        public string DoddleNowConnectionString2 {
            get {
                return ((string)(this["DoddleNowConnectionString2"]));
            }
        }
    }
}
