<?xml version="1.0" encoding="utf-8"?><Database Name="DoddleNow" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=appidentity.c6qpaqe4bu02.us-west-2.rds.amazonaws.com,1433;Initial Catalog=DoddleNow;Integrated Security=False;User ID=DoddleApplication;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="DoddleNowConnectionString2" Provider="System.Data.SqlClient" />
</Database>